// 260927 §6.3 p-1/p-2: 페기 구(p) 블루프린트 2종. §4.2 규칙(P1~P16) 중 이번 단계에서 실제로
// 반영한 것: P1(두 얼굴 130/102), P2(DJ 인트로), P4(브레이크→halfBeat→build→drop),
// P6(스윙), P9(베이스 2마디 루프), P12(찬트 후크), P13(신스 폭).
//
// ponytail(단순화, 브라우저 청취 후 필요하면 보강):
// - form%8 안의 구조 변형(두 번째 브레이크 유무·인트로 순서·아웃트로 종류)은 아직 안 만든다
//   — 표의 기본 순서 하나로 고정.
// - halfBeat/break의 "브레이크 코드"·chord 레이어는 별도로 안 만들고 기존 pad 레이어(v2부터
//   있던 schedulePad, renderArrangement가 이미 모든 블루프린트에 대해 처리한다)를 그대로
//   재사용한다 — 화성적으로는 곡의 대표 코드가 계속 울리는 정도로 근사한다.
import type { Blueprint, LayerCue, LayerId } from "../blueprint";

function cue(layer: LayerId, extra: Partial<LayerCue> = {}): LayerCue {
  return { layer, enterBar: 0, exitBarsBeforeEnd: 0, rateSteps: [{ atBar: 0, rate: 16, density: 255 }], ...extra };
}

export const clubHouse: Blueprint = {
  id: "clubHouse",
  style: "p",
  tempoRange: [117, 132],
  swing: 0.19,
  roundTo: 4,
  kitFamily: "house",
  sidechain: { synthDb: -3, bassDb: -3, releaseBeats: 0.4 },
  synthWidth: 0.8,
  sections: [
    {
      id: "djIntro",
      bars: 4,
      intensity: 0.7,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("bass")],
    },
    {
      id: "synthIn",
      bars: 12,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("seqRiff")],
    },
    {
      id: "chant1",
      bars: 8,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("chop")],
    },
    {
      id: "full1",
      bars: 18,
      intensity: 0.85,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("chop"), cue("seqRiff")],
    },
    {
      id: "inst1",
      bars: 10,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("seqRiff")],
    },
    {
      id: "break",
      bars: 4,
      intensity: 0.45,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("seqRiff"), cue("chord")],
    },
    {
      id: "halfBeat",
      bars: 6,
      intensity: 0.55,
      drumFamily: "none",
      fill: [],
      drumGainDb: -20,
      filter: { from: 6000, to: 6000 },
      cues: [
        cue("kick", { rateSteps: [{ atBar: 0, rate: 4 }] }),
        cue("clap", { rateSteps: [{ atBar: 0, rate: 4 }] }),
        cue("chord"),
        cue("chop"),
        cue("seqRiff"),
      ],
      drumOverride: { kick: [4, 12], clap: [4, 12] },
    },
    {
      id: "drumsBack",
      bars: 1,
      intensity: 0.75,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc")],
    },
    {
      id: "drop",
      bars: 8,
      intensity: 0.9,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("chop")],
    },
    {
      id: "inst2",
      bars: 6,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass")],
    },
    {
      id: "chant2",
      bars: 8,
      intensity: 0.85,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("chop")],
    },
    {
      id: "break2",
      bars: 4,
      intensity: 0.45,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("seqRiff"), cue("chop")],
    },
    {
      id: "build",
      bars: 4,
      intensity: 0.9,
      drumFamily: "none",
      fill: [],
      endFill: "snareRoll16",
      filter: { from: 8000, to: 8000 },
      cues: [
        cue("kick"),
        cue("clap"),
        cue("hat"),
        cue("openHat"),
        cue("perc"),
        cue("bass"),
        cue("seqRiff"),
        cue("chop"),
        cue("riser"),
      ],
    },
    {
      id: "main",
      bars: 8,
      intensity: 0.9,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("openHat"), cue("perc"), cue("bass"), cue("seqRiff")],
    },
    {
      id: "outro",
      bars: 4,
      intensity: 0.6,
      drumFamily: "none",
      fill: [],
      filter: { from: 8000, to: 8000 },
      cues: [
        cue("kick"),
        cue("clap"),
        cue("hat", { rateSteps: [{ atBar: 0, rate: 16, density: 255 }] }),
        cue("openHat"),
        cue("perc"),
      ],
    },
    {
      id: "end",
      bars: 1,
      intensity: 0.15,
      drumFamily: "none",
      fill: [],
      endFill: "stop",
      filter: { from: 8000, to: 8000 },
      cues: [],
    },
  ],
};

export const slowJam: Blueprint = {
  id: "slowJam",
  style: "p",
  tempoRange: [117, 132],
  tempoScale: 0.8,
  swing: 0,
  roundTo: 4,
  kitFamily: "house",
  sidechain: { synthDb: -2, bassDb: -13, releaseBeats: 0.6 },
  synthWidth: 0.9,
  sections: [
    {
      id: "intro",
      bars: 4,
      intensity: 0.3,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("bass"), cue("chord")],
    },
    {
      id: "drumsIn",
      bars: 4,
      intensity: 0.6,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("chord")],
    },
    {
      id: "verse1",
      bars: 8,
      intensity: 0.65,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("chord"), cue("lead")],
    },
    {
      id: "pre",
      bars: 4,
      intensity: 0.6,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("lead")],
    },
    {
      id: "chorus1",
      bars: 12,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("lead"), cue("chord"), cue("chop")],
    },
    {
      id: "turn",
      bars: 2,
      intensity: 0.8,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [
        cue("kick"),
        cue("clap"),
        cue("hat", { rateSteps: [{ atBar: 0, rate: 16, density: 150 }] }),
        cue("bass"),
        cue("lead"),
        cue("chord"),
        cue("chop"),
      ],
    },
    {
      id: "verse2",
      bars: 8,
      intensity: 0.75,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("lead")],
    },
    {
      id: "chorus2",
      bars: 24,
      intensity: 0.85,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [cue("kick"), cue("clap"), cue("hat"), cue("bass"), cue("lead"), cue("chord"), cue("chop")],
    },
    {
      id: "outro",
      bars: 4,
      intensity: 0.55,
      drumFamily: "none",
      fill: [],
      filter: { from: 6000, to: 6000 },
      cues: [
        cue("kick"),
        cue("clap"),
        cue("hat", { rateSteps: [{ atBar: 0, rate: 16, density: 195 }] }),
        cue("bass"),
        cue("lead"),
        cue("chord"),
        cue("chop"),
      ],
    },
    {
      id: "end",
      bars: 2,
      intensity: 0.15,
      drumFamily: "none",
      fill: [],
      endFill: "stop",
      filter: { from: 6000, to: 6000 },
      cues: [],
    },
  ],
};

export const PEGGY_BLUEPRINTS: readonly Blueprint[] = [clubHouse, slowJam];

/** p 스타일 form(기수 12) → 블루프린트. v<8 clubHouse / v≥8 slowJam(§6.3 "form 필드 해석") —
 *  각 블루프린트 안의 구조 변형(비트 나머지)은 아직 안 쓴다(파일 위 comment 참고). */
export function pBlueprintIdFor(form: number): "clubHouse" | "slowJam" {
  return form < 8 ? "clubHouse" : "slowJam";
}
